language: ruby
script: bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-2
  - jruby-19mode
env:
  - "AS_VERSION=3.2.16"
  - "AS_VERSION=4.0.2"
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
